using System;
using System.Data;
using System.Data.SqlClient;

namespace MrTEK_EFatura
{
	public partial class Invoice
	{
		public SqlTransaction trans;

		public int InvoiceID = 0;
		public int Deleted = 0;
		public int CreatedBy = 0;
		public DateTime CreatedDate = new DateTime(1900,1,1);
		public int ModifiedBy = 0;
		public DateTime ModifiedDate = new DateTime(1900,1,1);
		public int IOType = 0;
		public string IntCode = "";
		public int LocalStatus = 0;
		public string IntegratorID = "";
		public int Status = 0;
		public string StatusDescription = "";
		public string PostBox = "";
		public int XsltNo = 0;
		public string ProfileID = "";
		public string ID = "";
		public string UUID = "";
		public DateTime IssueDate = new DateTime(1900,1,1);
		public DateTime IssueTime = new DateTime(1900,1,1);
		public string InvoiceTypeCode = "";
		public string DocumentCurrencyCode = "";
		public string TaxCurrencyCode = "";
		public string PricingCurrencyCode = "";
		public string PaymentCurrencyCode = "";
		public string PaymentAlternativeCurrencyCode = "";
		public int LineCountNumeric = 0;
		public DateTime InvoicePeriod_StartDate = new DateTime(1900,1,1);
		public DateTime InvoicePeriod_EndDate = new DateTime(1900,1,1);
		public string ASP_PartyIdentification1_schemeID = "";
		public string ASP_PartyIdentification1_ID = "";
		public string ASP_PartyIdentification2_schemeID = "";
		public string ASP_PartyIdentification2_ID = "";
		public string ASP_PartyIdentification3_schemeID = "";
		public string ASP_PartyIdentification3_ID = "";
		public string ASP_PartyIdentification4_schemeID = "";
		public string ASP_PartyIdentification4_ID = "";
		public string ASP_PartyIdentification5_schemeID = "";
		public string ASP_PartyIdentification5_ID = "";
		public string ASP_PartyName = "";
		public string ASP_PostalAddress_StreetName = "";
		public string ASP_PostalAddress_Room = "";
		public string ASP_PostalAddress_BuildingNumber = "";
		public string ASP_PostalAddress_BuildingName = "";
		public string ASP_PostalAddress_CitySubdivisionName = "";
		public string ASP_PostalAddress_CityName = "";
		public string ASP_PostalAddress_Country = "";
		public string ASP_PartyTaxSchemeName = "";
		public string ASP_PartyTaxSchemeTaxTypeCode = "";
		public string ASP_WebsiteURI = "";
		public string ASP_Contact_Telephone = "";
		public string ASP_Contact_Telefax = "";
		public string ASP_Contact_ElectronicMail = "";
		public string ASP_Person_FirstName = "";
		public string ASP_Person_FamilyName = "";
		public string ASP_Person_MiddleName = "";
		public string ASP_Person_NameSuffix = "";
		public string ASP_Person_Title = "";
		public string ASP_AgentParty_PartyIdentification1_schemeID = "";
		public string ASP_AgentParty_PartyIdentification1_ID = "";
		public string ASP_AgentParty_PartyIdentification2_schemeID = "";
		public string ASP_AgentParty_PartyIdentification2_ID = "";
		public string ASP_AgentParty_PartyIdentification3_schemeID = "";
		public string ASP_AgentParty_PartyIdentification3_ID = "";
		public string ASP_AgentParty_PartyIdentification4_schemeID = "";
		public string ASP_AgentParty_PartyIdentification4_ID = "";
		public string ASP_AgentParty_PartyIdentification5_schemeID = "";
		public string ASP_AgentParty_PartyIdentification5_ID = "";
		public string ASP_AgentParty_PartyName = "";
		public string ASP_AgentParty_PostalAddress_StreetName = "";
		public string ASP_AgentParty_PostalAddress_Room = "";
		public string ASP_AgentParty_PostalAddress_BuildingNumber = "";
		public string ASP_AgentParty_PostalAddress_BuildingName = "";
		public string ASP_AgentParty_PostalAddress_CitySubdivisionName = "";
		public string ASP_AgentParty_PostalAddress_CityName = "";
		public string ASP_AgentParty_PostalAddress_Country = "";
		public string ASP_AgentParty_PartyTaxSchemeName = "";
		public string ASP_AgentParty_PartyTaxSchemeTaxTypeCode = "";
		public string ASP_AgentParty_WebsiteURI = "";
		public string ASP_AgentParty_Contact_Telephone = "";
		public string ASP_AgentParty_Contact_Telefax = "";
		public string ASP_AgentParty_Contact_ElectronicMail = "";
		public string ASP_AgentParty_Person_FirstName = "";
		public string ASP_AgentParty_Person_FamilyName = "";
		public string ASP_AgentParty_Person_MiddleName = "";
		public string ASP_AgentParty_Person_NameSuffix = "";
		public string ASP_AgentParty_Person_Title = "";
		public string ACP_PartyIdentification1_schemeID = "";
		public string ACP_PartyIdentification1_ID = "";
		public string ACP_PartyIdentification2_schemeID = "";
		public string ACP_PartyIdentification2_ID = "";
		public string ACP_PartyIdentification3_schemeID = "";
		public string ACP_PartyIdentification3_ID = "";
		public string ACP_PartyIdentification4_schemeID = "";
		public string ACP_PartyIdentification4_ID = "";
		public string ACP_PartyIdentification5_schemeID = "";
		public string ACP_PartyIdentification5_ID = "";
		public string ACP_PartyName = "";
		public string ACP_PostalAddress_StreetName = "";
		public string ACP_PostalAddress_Room = "";
		public string ACP_PostalAddress_BuildingNumber = "";
		public string ACP_PostalAddress_BuildingName = "";
		public string ACP_PostalAddress_CitySubdivisionName = "";
		public string ACP_PostalAddress_CityName = "";
		public string ACP_PostalAddress_Country = "";
		public string ACP_PartyTaxSchemeName = "";
		public string ACP_PartyTaxSchemeTaxTypeCode = "";
		public string ACP_WebsiteURI = "";
		public string ACP_Contact_Telephone = "";
		public string ACP_Contact_Telefax = "";
		public string ACP_Contact_ElectronicMail = "";
		public string ACP_Person_FirstName = "";
		public string ACP_Person_FamilyName = "";
		public string ACP_Person_MiddleName = "";
		public string ACP_Person_NameSuffix = "";
		public string ACP_Person_Title = "";
		public string ACP_AgentParty_PartyIdentification1_schemeID = "";
		public string ACP_AgentParty_PartyIdentification1_ID = "";
		public string ACP_AgentParty_PartyIdentification2_schemeID = "";
		public string ACP_AgentParty_PartyIdentification2_ID = "";
		public string ACP_AgentParty_PartyIdentification3_schemeID = "";
		public string ACP_AgentParty_PartyIdentification3_ID = "";
		public string ACP_AgentParty_PartyIdentification4_schemeID = "";
		public string ACP_AgentParty_PartyIdentification4_ID = "";
		public string ACP_AgentParty_PartyIdentification5_schemeID = "";
		public string ACP_AgentParty_PartyIdentification5_ID = "";
		public string ACP_AgentParty_PartyName = "";
		public string ACP_AgentParty_PostalAddress_StreetName = "";
		public string ACP_AgentParty_PostalAddress_Room = "";
		public string ACP_AgentParty_PostalAddress_BuildingNumber = "";
		public string ACP_AgentParty_PostalAddress_BuildingName = "";
		public string ACP_AgentParty_PostalAddress_CitySubdivisionName = "";
		public string ACP_AgentParty_PostalAddress_CityName = "";
		public string ACP_AgentParty_PostalAddress_Country = "";
		public string ACP_AgentParty_PartyTaxSchemeName = "";
		public string ACP_AgentParty_PartyTaxSchemeTaxTypeCode = "";
		public string ACP_AgentParty_WebsiteURI = "";
		public string ACP_AgentParty_Contact_Telephone = "";
		public string ACP_AgentParty_Contact_Telefax = "";
		public string ACP_AgentParty_Contact_ElectronicMail = "";
		public string ACP_AgentParty_Person_FirstName = "";
		public string ACP_AgentParty_Person_FamilyName = "";
		public string ACP_AgentParty_Person_MiddleName = "";
		public string ACP_AgentParty_Person_NameSuffix = "";
		public string ACP_AgentParty_Person_Title = "";
		public string TaxExchangeRate_SourceCurrencyCode = "";
		public string TaxExchangeRate_TargetCurrencyCode = "";
		public double TaxExchangeRate_CalculationRate = 0;
		public DateTime TaxExchangeRate_Date = new DateTime(1900,1,1);
		public string PricingExchangeRate_SourceCurrencyCode = "";
		public string PricingExchangeRate_TargetCurrencyCode = "";
		public double PricingExchangeRate_CalculationRate = 0;
		public DateTime PricingExchangeRate_Date = new DateTime(1900,1,1);
		public string PaymentExchangeRate_SourceCurrencyCode = "";
		public string PaymentExchangeRate_TargetCurrencyCode = "";
		public double PaymentExchangeRate_CalculationRate = 0;
		public DateTime PaymentExchangeRate_Date = new DateTime(1900,1,1);
		public string PaymentAlternativeExchangeRate_SourceCurrencyCode = "";
		public string PaymentAlternativeExchangeRate_TargetCurrencyCode = "";
		public double PaymentAlternativeExchangeRate_CalculationRate = 0;
		public DateTime PaymentAlternativeExchangeRate_Date = new DateTime(1900,1,1);
		public double TaxAmount = 0;
		public double LegalMonetaryTotal_LineExtensionAmount = 0;
		public double LegalMonetaryTotal_TaxExclusiveAmount = 0;
		public double LegalMonetaryTotal_TaxInclusiveAmount = 0;
		public double LegalMonetaryTotal_AllowanceTotalAmount = 0;
		public double LegalMonetaryTotal_ChargeTotalAmount = 0;
		public double LegalMonetaryTotal_PayableRoundingAmount = 0;
		public double LegalMonetaryTotal_PayableAmount = 0;
		public double WithholdingTaxAmount = 0;
		public string Message = "";

		public bool Load()
		{
			SqlCommand cmd = new SqlCommand();
			SqlDataAdapter da;
			DataTable dt;
			cmd.Connection = DF.ActiveConn.dbConn;
			cmd.CommandText = "SELECT * FROM Invoice WHERE InvoiceID = " + this.InvoiceID;
			da = new SqlDataAdapter(cmd);
			dt = new DataTable();
			da.Fill(dt);
			if(dt.Rows.Count>0)
			{
				DataRow dr = dt.Rows[0];
				this.Deleted = (int)dr["Deleted"];
				this.CreatedBy = (int)dr["CreatedBy"];
				this.CreatedDate = (DateTime)dr["CreatedDate"];
				this.ModifiedBy = (int)dr["ModifiedBy"];
				this.ModifiedDate = (DateTime)dr["ModifiedDate"];
				this.IOType = (int)dr["IOType"];
				this.IntCode = dr["IntCode"].ToString();
				this.LocalStatus = (int)dr["LocalStatus"];
				this.IntegratorID = dr["IntegratorID"].ToString();
				this.Status = (int)dr["Status"];
				this.StatusDescription = dr["StatusDescription"].ToString();
				this.PostBox = dr["PostBox"].ToString();
				this.XsltNo = (int)dr["XsltNo"];
				this.ProfileID = dr["ProfileID"].ToString();
				this.ID = dr["ID"].ToString();
				this.UUID = dr["UUID"].ToString();
				this.IssueDate = (DateTime)dr["IssueDate"];
				this.IssueTime = (DateTime)dr["IssueTime"];
				this.InvoiceTypeCode = dr["InvoiceTypeCode"].ToString();
				this.DocumentCurrencyCode = dr["DocumentCurrencyCode"].ToString();
				this.TaxCurrencyCode = dr["TaxCurrencyCode"].ToString();
				this.PricingCurrencyCode = dr["PricingCurrencyCode"].ToString();
				this.PaymentCurrencyCode = dr["PaymentCurrencyCode"].ToString();
				this.PaymentAlternativeCurrencyCode = dr["PaymentAlternativeCurrencyCode"].ToString();
				this.LineCountNumeric = (int)dr["LineCountNumeric"];
				this.InvoicePeriod_StartDate = (DateTime)dr["InvoicePeriod_StartDate"];
				this.InvoicePeriod_EndDate = (DateTime)dr["InvoicePeriod_EndDate"];
				this.ASP_PartyIdentification1_schemeID = dr["ASP_PartyIdentification1_schemeID"].ToString();
				this.ASP_PartyIdentification1_ID = dr["ASP_PartyIdentification1_ID"].ToString();
				this.ASP_PartyIdentification2_schemeID = dr["ASP_PartyIdentification2_schemeID"].ToString();
				this.ASP_PartyIdentification2_ID = dr["ASP_PartyIdentification2_ID"].ToString();
				this.ASP_PartyIdentification3_schemeID = dr["ASP_PartyIdentification3_schemeID"].ToString();
				this.ASP_PartyIdentification3_ID = dr["ASP_PartyIdentification3_ID"].ToString();
				this.ASP_PartyIdentification4_schemeID = dr["ASP_PartyIdentification4_schemeID"].ToString();
				this.ASP_PartyIdentification4_ID = dr["ASP_PartyIdentification4_ID"].ToString();
				this.ASP_PartyIdentification5_schemeID = dr["ASP_PartyIdentification5_schemeID"].ToString();
				this.ASP_PartyIdentification5_ID = dr["ASP_PartyIdentification5_ID"].ToString();
				this.ASP_PartyName = dr["ASP_PartyName"].ToString();
				this.ASP_PostalAddress_StreetName = dr["ASP_PostalAddress_StreetName"].ToString();
				this.ASP_PostalAddress_Room = dr["ASP_PostalAddress_Room"].ToString();
				this.ASP_PostalAddress_BuildingNumber = dr["ASP_PostalAddress_BuildingNumber"].ToString();
				this.ASP_PostalAddress_BuildingName = dr["ASP_PostalAddress_BuildingName"].ToString();
				this.ASP_PostalAddress_CitySubdivisionName = dr["ASP_PostalAddress_CitySubdivisionName"].ToString();
				this.ASP_PostalAddress_CityName = dr["ASP_PostalAddress_CityName"].ToString();
				this.ASP_PostalAddress_Country = dr["ASP_PostalAddress_Country"].ToString();
				this.ASP_PartyTaxSchemeName = dr["ASP_PartyTaxSchemeName"].ToString();
				this.ASP_PartyTaxSchemeTaxTypeCode = dr["ASP_PartyTaxSchemeTaxTypeCode"].ToString();
				this.ASP_WebsiteURI = dr["ASP_WebsiteURI"].ToString();
				this.ASP_Contact_Telephone = dr["ASP_Contact_Telephone"].ToString();
				this.ASP_Contact_Telefax = dr["ASP_Contact_Telefax"].ToString();
				this.ASP_Contact_ElectronicMail = dr["ASP_Contact_ElectronicMail"].ToString();
				this.ASP_Person_FirstName = dr["ASP_Person_FirstName"].ToString();
				this.ASP_Person_FamilyName = dr["ASP_Person_FamilyName"].ToString();
				this.ASP_Person_MiddleName = dr["ASP_Person_MiddleName"].ToString();
				this.ASP_Person_NameSuffix = dr["ASP_Person_NameSuffix"].ToString();
				this.ASP_Person_Title = dr["ASP_Person_Title"].ToString();
				this.ASP_AgentParty_PartyIdentification1_schemeID = dr["ASP_AgentParty_PartyIdentification1_schemeID"].ToString();
				this.ASP_AgentParty_PartyIdentification1_ID = dr["ASP_AgentParty_PartyIdentification1_ID"].ToString();
				this.ASP_AgentParty_PartyIdentification2_schemeID = dr["ASP_AgentParty_PartyIdentification2_schemeID"].ToString();
				this.ASP_AgentParty_PartyIdentification2_ID = dr["ASP_AgentParty_PartyIdentification2_ID"].ToString();
				this.ASP_AgentParty_PartyIdentification3_schemeID = dr["ASP_AgentParty_PartyIdentification3_schemeID"].ToString();
				this.ASP_AgentParty_PartyIdentification3_ID = dr["ASP_AgentParty_PartyIdentification3_ID"].ToString();
				this.ASP_AgentParty_PartyIdentification4_schemeID = dr["ASP_AgentParty_PartyIdentification4_schemeID"].ToString();
				this.ASP_AgentParty_PartyIdentification4_ID = dr["ASP_AgentParty_PartyIdentification4_ID"].ToString();
				this.ASP_AgentParty_PartyIdentification5_schemeID = dr["ASP_AgentParty_PartyIdentification5_schemeID"].ToString();
				this.ASP_AgentParty_PartyIdentification5_ID = dr["ASP_AgentParty_PartyIdentification5_ID"].ToString();
				this.ASP_AgentParty_PartyName = dr["ASP_AgentParty_PartyName"].ToString();
				this.ASP_AgentParty_PostalAddress_StreetName = dr["ASP_AgentParty_PostalAddress_StreetName"].ToString();
				this.ASP_AgentParty_PostalAddress_Room = dr["ASP_AgentParty_PostalAddress_Room"].ToString();
				this.ASP_AgentParty_PostalAddress_BuildingNumber = dr["ASP_AgentParty_PostalAddress_BuildingNumber"].ToString();
				this.ASP_AgentParty_PostalAddress_BuildingName = dr["ASP_AgentParty_PostalAddress_BuildingName"].ToString();
				this.ASP_AgentParty_PostalAddress_CitySubdivisionName = dr["ASP_AgentParty_PostalAddress_CitySubdivisionName"].ToString();
				this.ASP_AgentParty_PostalAddress_CityName = dr["ASP_AgentParty_PostalAddress_CityName"].ToString();
				this.ASP_AgentParty_PostalAddress_Country = dr["ASP_AgentParty_PostalAddress_Country"].ToString();
				this.ASP_AgentParty_PartyTaxSchemeName = dr["ASP_AgentParty_PartyTaxSchemeName"].ToString();
				this.ASP_AgentParty_PartyTaxSchemeTaxTypeCode = dr["ASP_AgentParty_PartyTaxSchemeTaxTypeCode"].ToString();
				this.ASP_AgentParty_WebsiteURI = dr["ASP_AgentParty_WebsiteURI"].ToString();
				this.ASP_AgentParty_Contact_Telephone = dr["ASP_AgentParty_Contact_Telephone"].ToString();
				this.ASP_AgentParty_Contact_Telefax = dr["ASP_AgentParty_Contact_Telefax"].ToString();
				this.ASP_AgentParty_Contact_ElectronicMail = dr["ASP_AgentParty_Contact_ElectronicMail"].ToString();
				this.ASP_AgentParty_Person_FirstName = dr["ASP_AgentParty_Person_FirstName"].ToString();
				this.ASP_AgentParty_Person_FamilyName = dr["ASP_AgentParty_Person_FamilyName"].ToString();
				this.ASP_AgentParty_Person_MiddleName = dr["ASP_AgentParty_Person_MiddleName"].ToString();
				this.ASP_AgentParty_Person_NameSuffix = dr["ASP_AgentParty_Person_NameSuffix"].ToString();
				this.ASP_AgentParty_Person_Title = dr["ASP_AgentParty_Person_Title"].ToString();
				this.ACP_PartyIdentification1_schemeID = dr["ACP_PartyIdentification1_schemeID"].ToString();
				this.ACP_PartyIdentification1_ID = dr["ACP_PartyIdentification1_ID"].ToString();
				this.ACP_PartyIdentification2_schemeID = dr["ACP_PartyIdentification2_schemeID"].ToString();
				this.ACP_PartyIdentification2_ID = dr["ACP_PartyIdentification2_ID"].ToString();
				this.ACP_PartyIdentification3_schemeID = dr["ACP_PartyIdentification3_schemeID"].ToString();
				this.ACP_PartyIdentification3_ID = dr["ACP_PartyIdentification3_ID"].ToString();
				this.ACP_PartyIdentification4_schemeID = dr["ACP_PartyIdentification4_schemeID"].ToString();
				this.ACP_PartyIdentification4_ID = dr["ACP_PartyIdentification4_ID"].ToString();
				this.ACP_PartyIdentification5_schemeID = dr["ACP_PartyIdentification5_schemeID"].ToString();
				this.ACP_PartyIdentification5_ID = dr["ACP_PartyIdentification5_ID"].ToString();
				this.ACP_PartyName = dr["ACP_PartyName"].ToString();
				this.ACP_PostalAddress_StreetName = dr["ACP_PostalAddress_StreetName"].ToString();
				this.ACP_PostalAddress_Room = dr["ACP_PostalAddress_Room"].ToString();
				this.ACP_PostalAddress_BuildingNumber = dr["ACP_PostalAddress_BuildingNumber"].ToString();
				this.ACP_PostalAddress_BuildingName = dr["ACP_PostalAddress_BuildingName"].ToString();
				this.ACP_PostalAddress_CitySubdivisionName = dr["ACP_PostalAddress_CitySubdivisionName"].ToString();
				this.ACP_PostalAddress_CityName = dr["ACP_PostalAddress_CityName"].ToString();
				this.ACP_PostalAddress_Country = dr["ACP_PostalAddress_Country"].ToString();
				this.ACP_PartyTaxSchemeName = dr["ACP_PartyTaxSchemeName"].ToString();
				this.ACP_PartyTaxSchemeTaxTypeCode = dr["ACP_PartyTaxSchemeTaxTypeCode"].ToString();
				this.ACP_WebsiteURI = dr["ACP_WebsiteURI"].ToString();
				this.ACP_Contact_Telephone = dr["ACP_Contact_Telephone"].ToString();
				this.ACP_Contact_Telefax = dr["ACP_Contact_Telefax"].ToString();
				this.ACP_Contact_ElectronicMail = dr["ACP_Contact_ElectronicMail"].ToString();
				this.ACP_Person_FirstName = dr["ACP_Person_FirstName"].ToString();
				this.ACP_Person_FamilyName = dr["ACP_Person_FamilyName"].ToString();
				this.ACP_Person_MiddleName = dr["ACP_Person_MiddleName"].ToString();
				this.ACP_Person_NameSuffix = dr["ACP_Person_NameSuffix"].ToString();
				this.ACP_Person_Title = dr["ACP_Person_Title"].ToString();
				this.ACP_AgentParty_PartyIdentification1_schemeID = dr["ACP_AgentParty_PartyIdentification1_schemeID"].ToString();
				this.ACP_AgentParty_PartyIdentification1_ID = dr["ACP_AgentParty_PartyIdentification1_ID"].ToString();
				this.ACP_AgentParty_PartyIdentification2_schemeID = dr["ACP_AgentParty_PartyIdentification2_schemeID"].ToString();
				this.ACP_AgentParty_PartyIdentification2_ID = dr["ACP_AgentParty_PartyIdentification2_ID"].ToString();
				this.ACP_AgentParty_PartyIdentification3_schemeID = dr["ACP_AgentParty_PartyIdentification3_schemeID"].ToString();
				this.ACP_AgentParty_PartyIdentification3_ID = dr["ACP_AgentParty_PartyIdentification3_ID"].ToString();
				this.ACP_AgentParty_PartyIdentification4_schemeID = dr["ACP_AgentParty_PartyIdentification4_schemeID"].ToString();
				this.ACP_AgentParty_PartyIdentification4_ID = dr["ACP_AgentParty_PartyIdentification4_ID"].ToString();
				this.ACP_AgentParty_PartyIdentification5_schemeID = dr["ACP_AgentParty_PartyIdentification5_schemeID"].ToString();
				this.ACP_AgentParty_PartyIdentification5_ID = dr["ACP_AgentParty_PartyIdentification5_ID"].ToString();
				this.ACP_AgentParty_PartyName = dr["ACP_AgentParty_PartyName"].ToString();
				this.ACP_AgentParty_PostalAddress_StreetName = dr["ACP_AgentParty_PostalAddress_StreetName"].ToString();
				this.ACP_AgentParty_PostalAddress_Room = dr["ACP_AgentParty_PostalAddress_Room"].ToString();
				this.ACP_AgentParty_PostalAddress_BuildingNumber = dr["ACP_AgentParty_PostalAddress_BuildingNumber"].ToString();
				this.ACP_AgentParty_PostalAddress_BuildingName = dr["ACP_AgentParty_PostalAddress_BuildingName"].ToString();
				this.ACP_AgentParty_PostalAddress_CitySubdivisionName = dr["ACP_AgentParty_PostalAddress_CitySubdivisionName"].ToString();
				this.ACP_AgentParty_PostalAddress_CityName = dr["ACP_AgentParty_PostalAddress_CityName"].ToString();
				this.ACP_AgentParty_PostalAddress_Country = dr["ACP_AgentParty_PostalAddress_Country"].ToString();
				this.ACP_AgentParty_PartyTaxSchemeName = dr["ACP_AgentParty_PartyTaxSchemeName"].ToString();
				this.ACP_AgentParty_PartyTaxSchemeTaxTypeCode = dr["ACP_AgentParty_PartyTaxSchemeTaxTypeCode"].ToString();
				this.ACP_AgentParty_WebsiteURI = dr["ACP_AgentParty_WebsiteURI"].ToString();
				this.ACP_AgentParty_Contact_Telephone = dr["ACP_AgentParty_Contact_Telephone"].ToString();
				this.ACP_AgentParty_Contact_Telefax = dr["ACP_AgentParty_Contact_Telefax"].ToString();
				this.ACP_AgentParty_Contact_ElectronicMail = dr["ACP_AgentParty_Contact_ElectronicMail"].ToString();
				this.ACP_AgentParty_Person_FirstName = dr["ACP_AgentParty_Person_FirstName"].ToString();
				this.ACP_AgentParty_Person_FamilyName = dr["ACP_AgentParty_Person_FamilyName"].ToString();
				this.ACP_AgentParty_Person_MiddleName = dr["ACP_AgentParty_Person_MiddleName"].ToString();
				this.ACP_AgentParty_Person_NameSuffix = dr["ACP_AgentParty_Person_NameSuffix"].ToString();
				this.ACP_AgentParty_Person_Title = dr["ACP_AgentParty_Person_Title"].ToString();
				this.TaxExchangeRate_SourceCurrencyCode = dr["TaxExchangeRate_SourceCurrencyCode"].ToString();
				this.TaxExchangeRate_TargetCurrencyCode = dr["TaxExchangeRate_TargetCurrencyCode"].ToString();
				this.TaxExchangeRate_CalculationRate = (double)dr["TaxExchangeRate_CalculationRate"];
				this.TaxExchangeRate_Date = (DateTime)dr["TaxExchangeRate_Date"];
				this.PricingExchangeRate_SourceCurrencyCode = dr["PricingExchangeRate_SourceCurrencyCode"].ToString();
				this.PricingExchangeRate_TargetCurrencyCode = dr["PricingExchangeRate_TargetCurrencyCode"].ToString();
				this.PricingExchangeRate_CalculationRate = (double)dr["PricingExchangeRate_CalculationRate"];
				this.PricingExchangeRate_Date = (DateTime)dr["PricingExchangeRate_Date"];
				this.PaymentExchangeRate_SourceCurrencyCode = dr["PaymentExchangeRate_SourceCurrencyCode"].ToString();
				this.PaymentExchangeRate_TargetCurrencyCode = dr["PaymentExchangeRate_TargetCurrencyCode"].ToString();
				this.PaymentExchangeRate_CalculationRate = (double)dr["PaymentExchangeRate_CalculationRate"];
				this.PaymentExchangeRate_Date = (DateTime)dr["PaymentExchangeRate_Date"];
				this.PaymentAlternativeExchangeRate_SourceCurrencyCode = dr["PaymentAlternativeExchangeRate_SourceCurrencyCode"].ToString();
				this.PaymentAlternativeExchangeRate_TargetCurrencyCode = dr["PaymentAlternativeExchangeRate_TargetCurrencyCode"].ToString();
				this.PaymentAlternativeExchangeRate_CalculationRate = (double)dr["PaymentAlternativeExchangeRate_CalculationRate"];
				this.PaymentAlternativeExchangeRate_Date = (DateTime)dr["PaymentAlternativeExchangeRate_Date"];
				this.TaxAmount = (double)dr["TaxAmount"];
				this.LegalMonetaryTotal_LineExtensionAmount = (double)dr["LegalMonetaryTotal_LineExtensionAmount"];
				this.LegalMonetaryTotal_TaxExclusiveAmount = (double)dr["LegalMonetaryTotal_TaxExclusiveAmount"];
				this.LegalMonetaryTotal_TaxInclusiveAmount = (double)dr["LegalMonetaryTotal_TaxInclusiveAmount"];
				this.LegalMonetaryTotal_AllowanceTotalAmount = (double)dr["LegalMonetaryTotal_AllowanceTotalAmount"];
				this.LegalMonetaryTotal_ChargeTotalAmount = (double)dr["LegalMonetaryTotal_ChargeTotalAmount"];
				this.LegalMonetaryTotal_PayableRoundingAmount = (double)dr["LegalMonetaryTotal_PayableRoundingAmount"];
				this.LegalMonetaryTotal_PayableAmount = (double)dr["LegalMonetaryTotal_PayableAmount"];
				this.WithholdingTaxAmount = (double)dr["WithholdingTaxAmount"];
				this.Message = dr["Message"].ToString();
				return true;
			}else{
				return false;
			}
		}

		public bool Save()
		{
			SqlCommand cmd = new SqlCommand();
			SqlDataAdapter da;
			System.Data.DataTable dt;
			cmd.Connection = DF.ActiveConn.dbConn;
			if (this.trans != null) cmd.Transaction = trans;
			cmd.Parameters.Clear();
			cmd.Parameters.Add(new SqlParameter("@InvoiceID", this.InvoiceID));
			cmd.Parameters.Add(new SqlParameter("@Deleted", this.Deleted));
			cmd.Parameters.Add(new SqlParameter("@IOType", this.IOType));
			cmd.Parameters.Add(new SqlParameter("@IntCode", this.IntCode.Substring(0,this.IntCode.Length>50?50:this.IntCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@LocalStatus", this.LocalStatus));
			cmd.Parameters.Add(new SqlParameter("@IntegratorID", this.IntegratorID.Substring(0,this.IntegratorID.Length>50?50:this.IntegratorID.Length )));
			cmd.Parameters.Add(new SqlParameter("@Status", this.Status));
			cmd.Parameters.Add(new SqlParameter("@StatusDescription", this.StatusDescription.Substring(0,this.StatusDescription.Length>50?50:this.StatusDescription.Length )));
			cmd.Parameters.Add(new SqlParameter("@PostBox", this.PostBox.Substring(0,this.PostBox.Length>100?100:this.PostBox.Length )));
			cmd.Parameters.Add(new SqlParameter("@XsltNo", this.XsltNo));
			cmd.Parameters.Add(new SqlParameter("@ProfileID", this.ProfileID.Substring(0,this.ProfileID.Length>50?50:this.ProfileID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ID", this.ID.Substring(0,this.ID.Length>16?16:this.ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@UUID", this.UUID.Substring(0,this.UUID.Length>50?50:this.UUID.Length )));
			cmd.Parameters.Add(new SqlParameter("@IssueDate", this.IssueDate));
			cmd.Parameters.Add(new SqlParameter("@IssueTime", this.IssueTime));
			cmd.Parameters.Add(new SqlParameter("@InvoiceTypeCode", this.InvoiceTypeCode.Substring(0,this.InvoiceTypeCode.Length>15?15:this.InvoiceTypeCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@DocumentCurrencyCode", this.DocumentCurrencyCode.Substring(0,this.DocumentCurrencyCode.Length>5?5:this.DocumentCurrencyCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@TaxCurrencyCode", this.TaxCurrencyCode.Substring(0,this.TaxCurrencyCode.Length>5?5:this.TaxCurrencyCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@PricingCurrencyCode", this.PricingCurrencyCode.Substring(0,this.PricingCurrencyCode.Length>5?5:this.PricingCurrencyCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@PaymentCurrencyCode", this.PaymentCurrencyCode.Substring(0,this.PaymentCurrencyCode.Length>5?5:this.PaymentCurrencyCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@PaymentAlternativeCurrencyCode", this.PaymentAlternativeCurrencyCode.Substring(0,this.PaymentAlternativeCurrencyCode.Length>5?5:this.PaymentAlternativeCurrencyCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@LineCountNumeric", this.LineCountNumeric));
			cmd.Parameters.Add(new SqlParameter("@InvoicePeriod_StartDate", this.InvoicePeriod_StartDate));
			cmd.Parameters.Add(new SqlParameter("@InvoicePeriod_EndDate", this.InvoicePeriod_EndDate));
			cmd.Parameters.Add(new SqlParameter("@ASP_PartyIdentification1_schemeID", this.ASP_PartyIdentification1_schemeID.Substring(0,this.ASP_PartyIdentification1_schemeID.Length>50?50:this.ASP_PartyIdentification1_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PartyIdentification1_ID", this.ASP_PartyIdentification1_ID.Substring(0,this.ASP_PartyIdentification1_ID.Length>50?50:this.ASP_PartyIdentification1_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PartyIdentification2_schemeID", this.ASP_PartyIdentification2_schemeID.Substring(0,this.ASP_PartyIdentification2_schemeID.Length>50?50:this.ASP_PartyIdentification2_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PartyIdentification2_ID", this.ASP_PartyIdentification2_ID.Substring(0,this.ASP_PartyIdentification2_ID.Length>50?50:this.ASP_PartyIdentification2_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PartyIdentification3_schemeID", this.ASP_PartyIdentification3_schemeID.Substring(0,this.ASP_PartyIdentification3_schemeID.Length>50?50:this.ASP_PartyIdentification3_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PartyIdentification3_ID", this.ASP_PartyIdentification3_ID.Substring(0,this.ASP_PartyIdentification3_ID.Length>50?50:this.ASP_PartyIdentification3_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PartyIdentification4_schemeID", this.ASP_PartyIdentification4_schemeID.Substring(0,this.ASP_PartyIdentification4_schemeID.Length>50?50:this.ASP_PartyIdentification4_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PartyIdentification4_ID", this.ASP_PartyIdentification4_ID.Substring(0,this.ASP_PartyIdentification4_ID.Length>50?50:this.ASP_PartyIdentification4_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PartyIdentification5_schemeID", this.ASP_PartyIdentification5_schemeID.Substring(0,this.ASP_PartyIdentification5_schemeID.Length>50?50:this.ASP_PartyIdentification5_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PartyIdentification5_ID", this.ASP_PartyIdentification5_ID.Substring(0,this.ASP_PartyIdentification5_ID.Length>50?50:this.ASP_PartyIdentification5_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PartyName", this.ASP_PartyName.Substring(0,this.ASP_PartyName.Length>255?255:this.ASP_PartyName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PostalAddress_StreetName", this.ASP_PostalAddress_StreetName.Substring(0,this.ASP_PostalAddress_StreetName.Length>255?255:this.ASP_PostalAddress_StreetName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PostalAddress_Room", this.ASP_PostalAddress_Room.Substring(0,this.ASP_PostalAddress_Room.Length>50?50:this.ASP_PostalAddress_Room.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PostalAddress_BuildingNumber", this.ASP_PostalAddress_BuildingNumber.Substring(0,this.ASP_PostalAddress_BuildingNumber.Length>255?255:this.ASP_PostalAddress_BuildingNumber.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PostalAddress_BuildingName", this.ASP_PostalAddress_BuildingName.Substring(0,this.ASP_PostalAddress_BuildingName.Length>255?255:this.ASP_PostalAddress_BuildingName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PostalAddress_CitySubdivisionName", this.ASP_PostalAddress_CitySubdivisionName.Substring(0,this.ASP_PostalAddress_CitySubdivisionName.Length>255?255:this.ASP_PostalAddress_CitySubdivisionName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PostalAddress_CityName", this.ASP_PostalAddress_CityName.Substring(0,this.ASP_PostalAddress_CityName.Length>50?50:this.ASP_PostalAddress_CityName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PostalAddress_Country", this.ASP_PostalAddress_Country.Substring(0,this.ASP_PostalAddress_Country.Length>50?50:this.ASP_PostalAddress_Country.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PartyTaxSchemeName", this.ASP_PartyTaxSchemeName.Substring(0,this.ASP_PartyTaxSchemeName.Length>255?255:this.ASP_PartyTaxSchemeName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_PartyTaxSchemeTaxTypeCode", this.ASP_PartyTaxSchemeTaxTypeCode.Substring(0,this.ASP_PartyTaxSchemeTaxTypeCode.Length>255?255:this.ASP_PartyTaxSchemeTaxTypeCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_WebsiteURI", this.ASP_WebsiteURI.Substring(0,this.ASP_WebsiteURI.Length>255?255:this.ASP_WebsiteURI.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_Contact_Telephone", this.ASP_Contact_Telephone.Substring(0,this.ASP_Contact_Telephone.Length>50?50:this.ASP_Contact_Telephone.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_Contact_Telefax", this.ASP_Contact_Telefax.Substring(0,this.ASP_Contact_Telefax.Length>50?50:this.ASP_Contact_Telefax.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_Contact_ElectronicMail", this.ASP_Contact_ElectronicMail.Substring(0,this.ASP_Contact_ElectronicMail.Length>100?100:this.ASP_Contact_ElectronicMail.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_Person_FirstName", this.ASP_Person_FirstName.Substring(0,this.ASP_Person_FirstName.Length>50?50:this.ASP_Person_FirstName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_Person_FamilyName", this.ASP_Person_FamilyName.Substring(0,this.ASP_Person_FamilyName.Length>50?50:this.ASP_Person_FamilyName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_Person_MiddleName", this.ASP_Person_MiddleName.Substring(0,this.ASP_Person_MiddleName.Length>50?50:this.ASP_Person_MiddleName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_Person_NameSuffix", this.ASP_Person_NameSuffix.Substring(0,this.ASP_Person_NameSuffix.Length>50?50:this.ASP_Person_NameSuffix.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_Person_Title", this.ASP_Person_Title.Substring(0,this.ASP_Person_Title.Length>50?50:this.ASP_Person_Title.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PartyIdentification1_schemeID", this.ASP_AgentParty_PartyIdentification1_schemeID.Substring(0,this.ASP_AgentParty_PartyIdentification1_schemeID.Length>50?50:this.ASP_AgentParty_PartyIdentification1_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PartyIdentification1_ID", this.ASP_AgentParty_PartyIdentification1_ID.Substring(0,this.ASP_AgentParty_PartyIdentification1_ID.Length>50?50:this.ASP_AgentParty_PartyIdentification1_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PartyIdentification2_schemeID", this.ASP_AgentParty_PartyIdentification2_schemeID.Substring(0,this.ASP_AgentParty_PartyIdentification2_schemeID.Length>50?50:this.ASP_AgentParty_PartyIdentification2_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PartyIdentification2_ID", this.ASP_AgentParty_PartyIdentification2_ID.Substring(0,this.ASP_AgentParty_PartyIdentification2_ID.Length>50?50:this.ASP_AgentParty_PartyIdentification2_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PartyIdentification3_schemeID", this.ASP_AgentParty_PartyIdentification3_schemeID.Substring(0,this.ASP_AgentParty_PartyIdentification3_schemeID.Length>50?50:this.ASP_AgentParty_PartyIdentification3_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PartyIdentification3_ID", this.ASP_AgentParty_PartyIdentification3_ID.Substring(0,this.ASP_AgentParty_PartyIdentification3_ID.Length>50?50:this.ASP_AgentParty_PartyIdentification3_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PartyIdentification4_schemeID", this.ASP_AgentParty_PartyIdentification4_schemeID.Substring(0,this.ASP_AgentParty_PartyIdentification4_schemeID.Length>50?50:this.ASP_AgentParty_PartyIdentification4_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PartyIdentification4_ID", this.ASP_AgentParty_PartyIdentification4_ID.Substring(0,this.ASP_AgentParty_PartyIdentification4_ID.Length>50?50:this.ASP_AgentParty_PartyIdentification4_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PartyIdentification5_schemeID", this.ASP_AgentParty_PartyIdentification5_schemeID.Substring(0,this.ASP_AgentParty_PartyIdentification5_schemeID.Length>50?50:this.ASP_AgentParty_PartyIdentification5_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PartyIdentification5_ID", this.ASP_AgentParty_PartyIdentification5_ID.Substring(0,this.ASP_AgentParty_PartyIdentification5_ID.Length>50?50:this.ASP_AgentParty_PartyIdentification5_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PartyName", this.ASP_AgentParty_PartyName.Substring(0,this.ASP_AgentParty_PartyName.Length>255?255:this.ASP_AgentParty_PartyName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PostalAddress_StreetName", this.ASP_AgentParty_PostalAddress_StreetName.Substring(0,this.ASP_AgentParty_PostalAddress_StreetName.Length>255?255:this.ASP_AgentParty_PostalAddress_StreetName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PostalAddress_Room", this.ASP_AgentParty_PostalAddress_Room.Substring(0,this.ASP_AgentParty_PostalAddress_Room.Length>50?50:this.ASP_AgentParty_PostalAddress_Room.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PostalAddress_BuildingNumber", this.ASP_AgentParty_PostalAddress_BuildingNumber.Substring(0,this.ASP_AgentParty_PostalAddress_BuildingNumber.Length>255?255:this.ASP_AgentParty_PostalAddress_BuildingNumber.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PostalAddress_BuildingName", this.ASP_AgentParty_PostalAddress_BuildingName.Substring(0,this.ASP_AgentParty_PostalAddress_BuildingName.Length>255?255:this.ASP_AgentParty_PostalAddress_BuildingName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PostalAddress_CitySubdivisionName", this.ASP_AgentParty_PostalAddress_CitySubdivisionName.Substring(0,this.ASP_AgentParty_PostalAddress_CitySubdivisionName.Length>255?255:this.ASP_AgentParty_PostalAddress_CitySubdivisionName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PostalAddress_CityName", this.ASP_AgentParty_PostalAddress_CityName.Substring(0,this.ASP_AgentParty_PostalAddress_CityName.Length>50?50:this.ASP_AgentParty_PostalAddress_CityName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PostalAddress_Country", this.ASP_AgentParty_PostalAddress_Country.Substring(0,this.ASP_AgentParty_PostalAddress_Country.Length>50?50:this.ASP_AgentParty_PostalAddress_Country.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PartyTaxSchemeName", this.ASP_AgentParty_PartyTaxSchemeName.Substring(0,this.ASP_AgentParty_PartyTaxSchemeName.Length>255?255:this.ASP_AgentParty_PartyTaxSchemeName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_PartyTaxSchemeTaxTypeCode", this.ASP_AgentParty_PartyTaxSchemeTaxTypeCode.Substring(0,this.ASP_AgentParty_PartyTaxSchemeTaxTypeCode.Length>255?255:this.ASP_AgentParty_PartyTaxSchemeTaxTypeCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_WebsiteURI", this.ASP_AgentParty_WebsiteURI.Substring(0,this.ASP_AgentParty_WebsiteURI.Length>255?255:this.ASP_AgentParty_WebsiteURI.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_Contact_Telephone", this.ASP_AgentParty_Contact_Telephone.Substring(0,this.ASP_AgentParty_Contact_Telephone.Length>50?50:this.ASP_AgentParty_Contact_Telephone.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_Contact_Telefax", this.ASP_AgentParty_Contact_Telefax.Substring(0,this.ASP_AgentParty_Contact_Telefax.Length>50?50:this.ASP_AgentParty_Contact_Telefax.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_Contact_ElectronicMail", this.ASP_AgentParty_Contact_ElectronicMail.Substring(0,this.ASP_AgentParty_Contact_ElectronicMail.Length>100?100:this.ASP_AgentParty_Contact_ElectronicMail.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_Person_FirstName", this.ASP_AgentParty_Person_FirstName.Substring(0,this.ASP_AgentParty_Person_FirstName.Length>50?50:this.ASP_AgentParty_Person_FirstName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_Person_FamilyName", this.ASP_AgentParty_Person_FamilyName.Substring(0,this.ASP_AgentParty_Person_FamilyName.Length>50?50:this.ASP_AgentParty_Person_FamilyName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_Person_MiddleName", this.ASP_AgentParty_Person_MiddleName.Substring(0,this.ASP_AgentParty_Person_MiddleName.Length>50?50:this.ASP_AgentParty_Person_MiddleName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_Person_NameSuffix", this.ASP_AgentParty_Person_NameSuffix.Substring(0,this.ASP_AgentParty_Person_NameSuffix.Length>50?50:this.ASP_AgentParty_Person_NameSuffix.Length )));
			cmd.Parameters.Add(new SqlParameter("@ASP_AgentParty_Person_Title", this.ASP_AgentParty_Person_Title.Substring(0,this.ASP_AgentParty_Person_Title.Length>50?50:this.ASP_AgentParty_Person_Title.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PartyIdentification1_schemeID", this.ACP_PartyIdentification1_schemeID.Substring(0,this.ACP_PartyIdentification1_schemeID.Length>50?50:this.ACP_PartyIdentification1_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PartyIdentification1_ID", this.ACP_PartyIdentification1_ID.Substring(0,this.ACP_PartyIdentification1_ID.Length>50?50:this.ACP_PartyIdentification1_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PartyIdentification2_schemeID", this.ACP_PartyIdentification2_schemeID.Substring(0,this.ACP_PartyIdentification2_schemeID.Length>50?50:this.ACP_PartyIdentification2_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PartyIdentification2_ID", this.ACP_PartyIdentification2_ID.Substring(0,this.ACP_PartyIdentification2_ID.Length>50?50:this.ACP_PartyIdentification2_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PartyIdentification3_schemeID", this.ACP_PartyIdentification3_schemeID.Substring(0,this.ACP_PartyIdentification3_schemeID.Length>50?50:this.ACP_PartyIdentification3_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PartyIdentification3_ID", this.ACP_PartyIdentification3_ID.Substring(0,this.ACP_PartyIdentification3_ID.Length>50?50:this.ACP_PartyIdentification3_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PartyIdentification4_schemeID", this.ACP_PartyIdentification4_schemeID.Substring(0,this.ACP_PartyIdentification4_schemeID.Length>50?50:this.ACP_PartyIdentification4_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PartyIdentification4_ID", this.ACP_PartyIdentification4_ID.Substring(0,this.ACP_PartyIdentification4_ID.Length>50?50:this.ACP_PartyIdentification4_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PartyIdentification5_schemeID", this.ACP_PartyIdentification5_schemeID.Substring(0,this.ACP_PartyIdentification5_schemeID.Length>50?50:this.ACP_PartyIdentification5_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PartyIdentification5_ID", this.ACP_PartyIdentification5_ID.Substring(0,this.ACP_PartyIdentification5_ID.Length>50?50:this.ACP_PartyIdentification5_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PartyName", this.ACP_PartyName.Substring(0,this.ACP_PartyName.Length>255?255:this.ACP_PartyName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PostalAddress_StreetName", this.ACP_PostalAddress_StreetName.Substring(0,this.ACP_PostalAddress_StreetName.Length>255?255:this.ACP_PostalAddress_StreetName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PostalAddress_Room", this.ACP_PostalAddress_Room.Substring(0,this.ACP_PostalAddress_Room.Length>50?50:this.ACP_PostalAddress_Room.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PostalAddress_BuildingNumber", this.ACP_PostalAddress_BuildingNumber.Substring(0,this.ACP_PostalAddress_BuildingNumber.Length>255?255:this.ACP_PostalAddress_BuildingNumber.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PostalAddress_BuildingName", this.ACP_PostalAddress_BuildingName.Substring(0,this.ACP_PostalAddress_BuildingName.Length>255?255:this.ACP_PostalAddress_BuildingName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PostalAddress_CitySubdivisionName", this.ACP_PostalAddress_CitySubdivisionName.Substring(0,this.ACP_PostalAddress_CitySubdivisionName.Length>255?255:this.ACP_PostalAddress_CitySubdivisionName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PostalAddress_CityName", this.ACP_PostalAddress_CityName.Substring(0,this.ACP_PostalAddress_CityName.Length>50?50:this.ACP_PostalAddress_CityName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PostalAddress_Country", this.ACP_PostalAddress_Country.Substring(0,this.ACP_PostalAddress_Country.Length>50?50:this.ACP_PostalAddress_Country.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PartyTaxSchemeName", this.ACP_PartyTaxSchemeName.Substring(0,this.ACP_PartyTaxSchemeName.Length>255?255:this.ACP_PartyTaxSchemeName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_PartyTaxSchemeTaxTypeCode", this.ACP_PartyTaxSchemeTaxTypeCode.Substring(0,this.ACP_PartyTaxSchemeTaxTypeCode.Length>255?255:this.ACP_PartyTaxSchemeTaxTypeCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_WebsiteURI", this.ACP_WebsiteURI.Substring(0,this.ACP_WebsiteURI.Length>255?255:this.ACP_WebsiteURI.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_Contact_Telephone", this.ACP_Contact_Telephone.Substring(0,this.ACP_Contact_Telephone.Length>50?50:this.ACP_Contact_Telephone.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_Contact_Telefax", this.ACP_Contact_Telefax.Substring(0,this.ACP_Contact_Telefax.Length>50?50:this.ACP_Contact_Telefax.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_Contact_ElectronicMail", this.ACP_Contact_ElectronicMail.Substring(0,this.ACP_Contact_ElectronicMail.Length>100?100:this.ACP_Contact_ElectronicMail.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_Person_FirstName", this.ACP_Person_FirstName.Substring(0,this.ACP_Person_FirstName.Length>50?50:this.ACP_Person_FirstName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_Person_FamilyName", this.ACP_Person_FamilyName.Substring(0,this.ACP_Person_FamilyName.Length>50?50:this.ACP_Person_FamilyName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_Person_MiddleName", this.ACP_Person_MiddleName.Substring(0,this.ACP_Person_MiddleName.Length>50?50:this.ACP_Person_MiddleName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_Person_NameSuffix", this.ACP_Person_NameSuffix.Substring(0,this.ACP_Person_NameSuffix.Length>50?50:this.ACP_Person_NameSuffix.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_Person_Title", this.ACP_Person_Title.Substring(0,this.ACP_Person_Title.Length>50?50:this.ACP_Person_Title.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PartyIdentification1_schemeID", this.ACP_AgentParty_PartyIdentification1_schemeID.Substring(0,this.ACP_AgentParty_PartyIdentification1_schemeID.Length>50?50:this.ACP_AgentParty_PartyIdentification1_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PartyIdentification1_ID", this.ACP_AgentParty_PartyIdentification1_ID.Substring(0,this.ACP_AgentParty_PartyIdentification1_ID.Length>50?50:this.ACP_AgentParty_PartyIdentification1_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PartyIdentification2_schemeID", this.ACP_AgentParty_PartyIdentification2_schemeID.Substring(0,this.ACP_AgentParty_PartyIdentification2_schemeID.Length>50?50:this.ACP_AgentParty_PartyIdentification2_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PartyIdentification2_ID", this.ACP_AgentParty_PartyIdentification2_ID.Substring(0,this.ACP_AgentParty_PartyIdentification2_ID.Length>50?50:this.ACP_AgentParty_PartyIdentification2_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PartyIdentification3_schemeID", this.ACP_AgentParty_PartyIdentification3_schemeID.Substring(0,this.ACP_AgentParty_PartyIdentification3_schemeID.Length>50?50:this.ACP_AgentParty_PartyIdentification3_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PartyIdentification3_ID", this.ACP_AgentParty_PartyIdentification3_ID.Substring(0,this.ACP_AgentParty_PartyIdentification3_ID.Length>50?50:this.ACP_AgentParty_PartyIdentification3_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PartyIdentification4_schemeID", this.ACP_AgentParty_PartyIdentification4_schemeID.Substring(0,this.ACP_AgentParty_PartyIdentification4_schemeID.Length>50?50:this.ACP_AgentParty_PartyIdentification4_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PartyIdentification4_ID", this.ACP_AgentParty_PartyIdentification4_ID.Substring(0,this.ACP_AgentParty_PartyIdentification4_ID.Length>50?50:this.ACP_AgentParty_PartyIdentification4_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PartyIdentification5_schemeID", this.ACP_AgentParty_PartyIdentification5_schemeID.Substring(0,this.ACP_AgentParty_PartyIdentification5_schemeID.Length>50?50:this.ACP_AgentParty_PartyIdentification5_schemeID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PartyIdentification5_ID", this.ACP_AgentParty_PartyIdentification5_ID.Substring(0,this.ACP_AgentParty_PartyIdentification5_ID.Length>50?50:this.ACP_AgentParty_PartyIdentification5_ID.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PartyName", this.ACP_AgentParty_PartyName.Substring(0,this.ACP_AgentParty_PartyName.Length>255?255:this.ACP_AgentParty_PartyName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PostalAddress_StreetName", this.ACP_AgentParty_PostalAddress_StreetName.Substring(0,this.ACP_AgentParty_PostalAddress_StreetName.Length>255?255:this.ACP_AgentParty_PostalAddress_StreetName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PostalAddress_Room", this.ACP_AgentParty_PostalAddress_Room.Substring(0,this.ACP_AgentParty_PostalAddress_Room.Length>50?50:this.ACP_AgentParty_PostalAddress_Room.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PostalAddress_BuildingNumber", this.ACP_AgentParty_PostalAddress_BuildingNumber.Substring(0,this.ACP_AgentParty_PostalAddress_BuildingNumber.Length>255?255:this.ACP_AgentParty_PostalAddress_BuildingNumber.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PostalAddress_BuildingName", this.ACP_AgentParty_PostalAddress_BuildingName.Substring(0,this.ACP_AgentParty_PostalAddress_BuildingName.Length>255?255:this.ACP_AgentParty_PostalAddress_BuildingName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PostalAddress_CitySubdivisionName", this.ACP_AgentParty_PostalAddress_CitySubdivisionName.Substring(0,this.ACP_AgentParty_PostalAddress_CitySubdivisionName.Length>255?255:this.ACP_AgentParty_PostalAddress_CitySubdivisionName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PostalAddress_CityName", this.ACP_AgentParty_PostalAddress_CityName.Substring(0,this.ACP_AgentParty_PostalAddress_CityName.Length>50?50:this.ACP_AgentParty_PostalAddress_CityName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PostalAddress_Country", this.ACP_AgentParty_PostalAddress_Country.Substring(0,this.ACP_AgentParty_PostalAddress_Country.Length>50?50:this.ACP_AgentParty_PostalAddress_Country.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PartyTaxSchemeName", this.ACP_AgentParty_PartyTaxSchemeName.Substring(0,this.ACP_AgentParty_PartyTaxSchemeName.Length>255?255:this.ACP_AgentParty_PartyTaxSchemeName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_PartyTaxSchemeTaxTypeCode", this.ACP_AgentParty_PartyTaxSchemeTaxTypeCode.Substring(0,this.ACP_AgentParty_PartyTaxSchemeTaxTypeCode.Length>255?255:this.ACP_AgentParty_PartyTaxSchemeTaxTypeCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_WebsiteURI", this.ACP_AgentParty_WebsiteURI.Substring(0,this.ACP_AgentParty_WebsiteURI.Length>255?255:this.ACP_AgentParty_WebsiteURI.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_Contact_Telephone", this.ACP_AgentParty_Contact_Telephone.Substring(0,this.ACP_AgentParty_Contact_Telephone.Length>50?50:this.ACP_AgentParty_Contact_Telephone.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_Contact_Telefax", this.ACP_AgentParty_Contact_Telefax.Substring(0,this.ACP_AgentParty_Contact_Telefax.Length>50?50:this.ACP_AgentParty_Contact_Telefax.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_Contact_ElectronicMail", this.ACP_AgentParty_Contact_ElectronicMail.Substring(0,this.ACP_AgentParty_Contact_ElectronicMail.Length>100?100:this.ACP_AgentParty_Contact_ElectronicMail.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_Person_FirstName", this.ACP_AgentParty_Person_FirstName.Substring(0,this.ACP_AgentParty_Person_FirstName.Length>50?50:this.ACP_AgentParty_Person_FirstName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_Person_FamilyName", this.ACP_AgentParty_Person_FamilyName.Substring(0,this.ACP_AgentParty_Person_FamilyName.Length>50?50:this.ACP_AgentParty_Person_FamilyName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_Person_MiddleName", this.ACP_AgentParty_Person_MiddleName.Substring(0,this.ACP_AgentParty_Person_MiddleName.Length>50?50:this.ACP_AgentParty_Person_MiddleName.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_Person_NameSuffix", this.ACP_AgentParty_Person_NameSuffix.Substring(0,this.ACP_AgentParty_Person_NameSuffix.Length>50?50:this.ACP_AgentParty_Person_NameSuffix.Length )));
			cmd.Parameters.Add(new SqlParameter("@ACP_AgentParty_Person_Title", this.ACP_AgentParty_Person_Title.Substring(0,this.ACP_AgentParty_Person_Title.Length>50?50:this.ACP_AgentParty_Person_Title.Length )));
			cmd.Parameters.Add(new SqlParameter("@TaxExchangeRate_SourceCurrencyCode", this.TaxExchangeRate_SourceCurrencyCode.Substring(0,this.TaxExchangeRate_SourceCurrencyCode.Length>5?5:this.TaxExchangeRate_SourceCurrencyCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@TaxExchangeRate_TargetCurrencyCode", this.TaxExchangeRate_TargetCurrencyCode.Substring(0,this.TaxExchangeRate_TargetCurrencyCode.Length>5?5:this.TaxExchangeRate_TargetCurrencyCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@TaxExchangeRate_CalculationRate", this.TaxExchangeRate_CalculationRate));
			cmd.Parameters.Add(new SqlParameter("@TaxExchangeRate_Date", this.TaxExchangeRate_Date));
			cmd.Parameters.Add(new SqlParameter("@PricingExchangeRate_SourceCurrencyCode", this.PricingExchangeRate_SourceCurrencyCode.Substring(0,this.PricingExchangeRate_SourceCurrencyCode.Length>5?5:this.PricingExchangeRate_SourceCurrencyCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@PricingExchangeRate_TargetCurrencyCode", this.PricingExchangeRate_TargetCurrencyCode.Substring(0,this.PricingExchangeRate_TargetCurrencyCode.Length>5?5:this.PricingExchangeRate_TargetCurrencyCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@PricingExchangeRate_CalculationRate", this.PricingExchangeRate_CalculationRate));
			cmd.Parameters.Add(new SqlParameter("@PricingExchangeRate_Date", this.PricingExchangeRate_Date));
			cmd.Parameters.Add(new SqlParameter("@PaymentExchangeRate_SourceCurrencyCode", this.PaymentExchangeRate_SourceCurrencyCode.Substring(0,this.PaymentExchangeRate_SourceCurrencyCode.Length>5?5:this.PaymentExchangeRate_SourceCurrencyCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@PaymentExchangeRate_TargetCurrencyCode", this.PaymentExchangeRate_TargetCurrencyCode.Substring(0,this.PaymentExchangeRate_TargetCurrencyCode.Length>5?5:this.PaymentExchangeRate_TargetCurrencyCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@PaymentExchangeRate_CalculationRate", this.PaymentExchangeRate_CalculationRate));
			cmd.Parameters.Add(new SqlParameter("@PaymentExchangeRate_Date", this.PaymentExchangeRate_Date));
			cmd.Parameters.Add(new SqlParameter("@PaymentAlternativeExchangeRate_SourceCurrencyCode", this.PaymentAlternativeExchangeRate_SourceCurrencyCode.Substring(0,this.PaymentAlternativeExchangeRate_SourceCurrencyCode.Length>5?5:this.PaymentAlternativeExchangeRate_SourceCurrencyCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@PaymentAlternativeExchangeRate_TargetCurrencyCode", this.PaymentAlternativeExchangeRate_TargetCurrencyCode.Substring(0,this.PaymentAlternativeExchangeRate_TargetCurrencyCode.Length>5?5:this.PaymentAlternativeExchangeRate_TargetCurrencyCode.Length )));
			cmd.Parameters.Add(new SqlParameter("@PaymentAlternativeExchangeRate_CalculationRate", this.PaymentAlternativeExchangeRate_CalculationRate));
			cmd.Parameters.Add(new SqlParameter("@PaymentAlternativeExchangeRate_Date", this.PaymentAlternativeExchangeRate_Date));
			cmd.Parameters.Add(new SqlParameter("@TaxAmount", this.TaxAmount));
			cmd.Parameters.Add(new SqlParameter("@LegalMonetaryTotal_LineExtensionAmount", this.LegalMonetaryTotal_LineExtensionAmount));
			cmd.Parameters.Add(new SqlParameter("@LegalMonetaryTotal_TaxExclusiveAmount", this.LegalMonetaryTotal_TaxExclusiveAmount));
			cmd.Parameters.Add(new SqlParameter("@LegalMonetaryTotal_TaxInclusiveAmount", this.LegalMonetaryTotal_TaxInclusiveAmount));
			cmd.Parameters.Add(new SqlParameter("@LegalMonetaryTotal_AllowanceTotalAmount", this.LegalMonetaryTotal_AllowanceTotalAmount));
			cmd.Parameters.Add(new SqlParameter("@LegalMonetaryTotal_ChargeTotalAmount", this.LegalMonetaryTotal_ChargeTotalAmount));
			cmd.Parameters.Add(new SqlParameter("@LegalMonetaryTotal_PayableRoundingAmount", this.LegalMonetaryTotal_PayableRoundingAmount));
			cmd.Parameters.Add(new SqlParameter("@LegalMonetaryTotal_PayableAmount", this.LegalMonetaryTotal_PayableAmount));
			cmd.Parameters.Add(new SqlParameter("@WithholdingTaxAmount", this.WithholdingTaxAmount));
			cmd.Parameters.Add(new SqlParameter("@Message", this.Message.Substring(0,this.Message.Length>255?255:this.Message.Length )));

			if (InvoiceID == 0)
			{
				cmd.CommandText = "INSERT INTO Invoice (Deleted, CreatedBy, CreatedDate, ModifiedBy, ModifiedDate, IOType, IntCode, LocalStatus, IntegratorID, Status, StatusDescription, PostBox, XsltNo, ProfileID, ID, UUID, IssueDate, IssueTime, InvoiceTypeCode, DocumentCurrencyCode, TaxCurrencyCode, PricingCurrencyCode, PaymentCurrencyCode, PaymentAlternativeCurrencyCode, LineCountNumeric, InvoicePeriod_StartDate, InvoicePeriod_EndDate, ASP_PartyIdentification1_schemeID, ASP_PartyIdentification1_ID, ASP_PartyIdentification2_schemeID, ASP_PartyIdentification2_ID, ASP_PartyIdentification3_schemeID, ASP_PartyIdentification3_ID, ASP_PartyIdentification4_schemeID, ASP_PartyIdentification4_ID, ASP_PartyIdentification5_schemeID, ASP_PartyIdentification5_ID, ASP_PartyName, ASP_PostalAddress_StreetName, ASP_PostalAddress_Room, ASP_PostalAddress_BuildingNumber, ASP_PostalAddress_BuildingName, ASP_PostalAddress_CitySubdivisionName, ASP_PostalAddress_CityName, ASP_PostalAddress_Country, ASP_PartyTaxSchemeName, ASP_PartyTaxSchemeTaxTypeCode, ASP_WebsiteURI, ASP_Contact_Telephone, ASP_Contact_Telefax, ASP_Contact_ElectronicMail, ASP_Person_FirstName, ASP_Person_FamilyName, ASP_Person_MiddleName, ASP_Person_NameSuffix, ASP_Person_Title, ASP_AgentParty_PartyIdentification1_schemeID, ASP_AgentParty_PartyIdentification1_ID, ASP_AgentParty_PartyIdentification2_schemeID, ASP_AgentParty_PartyIdentification2_ID, ASP_AgentParty_PartyIdentification3_schemeID, ASP_AgentParty_PartyIdentification3_ID, ASP_AgentParty_PartyIdentification4_schemeID, ASP_AgentParty_PartyIdentification4_ID, ASP_AgentParty_PartyIdentification5_schemeID, ASP_AgentParty_PartyIdentification5_ID, ASP_AgentParty_PartyName, ASP_AgentParty_PostalAddress_StreetName, ASP_AgentParty_PostalAddress_Room, ASP_AgentParty_PostalAddress_BuildingNumber, ASP_AgentParty_PostalAddress_BuildingName, ASP_AgentParty_PostalAddress_CitySubdivisionName, ASP_AgentParty_PostalAddress_CityName, ASP_AgentParty_PostalAddress_Country, ASP_AgentParty_PartyTaxSchemeName, ASP_AgentParty_PartyTaxSchemeTaxTypeCode, ASP_AgentParty_WebsiteURI, ASP_AgentParty_Contact_Telephone, ASP_AgentParty_Contact_Telefax, ASP_AgentParty_Contact_ElectronicMail, ASP_AgentParty_Person_FirstName, ASP_AgentParty_Person_FamilyName, ASP_AgentParty_Person_MiddleName, ASP_AgentParty_Person_NameSuffix, ASP_AgentParty_Person_Title, ACP_PartyIdentification1_schemeID, ACP_PartyIdentification1_ID, ACP_PartyIdentification2_schemeID, ACP_PartyIdentification2_ID, ACP_PartyIdentification3_schemeID, ACP_PartyIdentification3_ID, ACP_PartyIdentification4_schemeID, ACP_PartyIdentification4_ID, ACP_PartyIdentification5_schemeID, ACP_PartyIdentification5_ID, ACP_PartyName, ACP_PostalAddress_StreetName, ACP_PostalAddress_Room, ACP_PostalAddress_BuildingNumber, ACP_PostalAddress_BuildingName, ACP_PostalAddress_CitySubdivisionName, ACP_PostalAddress_CityName, ACP_PostalAddress_Country, ACP_PartyTaxSchemeName, ACP_PartyTaxSchemeTaxTypeCode, ACP_WebsiteURI, ACP_Contact_Telephone, ACP_Contact_Telefax, ACP_Contact_ElectronicMail, ACP_Person_FirstName, ACP_Person_FamilyName, ACP_Person_MiddleName, ACP_Person_NameSuffix, ACP_Person_Title, ACP_AgentParty_PartyIdentification1_schemeID, ACP_AgentParty_PartyIdentification1_ID, ACP_AgentParty_PartyIdentification2_schemeID, ACP_AgentParty_PartyIdentification2_ID, ACP_AgentParty_PartyIdentification3_schemeID, ACP_AgentParty_PartyIdentification3_ID, ACP_AgentParty_PartyIdentification4_schemeID, ACP_AgentParty_PartyIdentification4_ID, ACP_AgentParty_PartyIdentification5_schemeID, ACP_AgentParty_PartyIdentification5_ID, ACP_AgentParty_PartyName, ACP_AgentParty_PostalAddress_StreetName, ACP_AgentParty_PostalAddress_Room, ACP_AgentParty_PostalAddress_BuildingNumber, ACP_AgentParty_PostalAddress_BuildingName, ACP_AgentParty_PostalAddress_CitySubdivisionName, ACP_AgentParty_PostalAddress_CityName, ACP_AgentParty_PostalAddress_Country, ACP_AgentParty_PartyTaxSchemeName, ACP_AgentParty_PartyTaxSchemeTaxTypeCode, ACP_AgentParty_WebsiteURI, ACP_AgentParty_Contact_Telephone, ACP_AgentParty_Contact_Telefax, ACP_AgentParty_Contact_ElectronicMail, ACP_AgentParty_Person_FirstName, ACP_AgentParty_Person_FamilyName, ACP_AgentParty_Person_MiddleName, ACP_AgentParty_Person_NameSuffix, ACP_AgentParty_Person_Title, TaxExchangeRate_SourceCurrencyCode, TaxExchangeRate_TargetCurrencyCode, TaxExchangeRate_CalculationRate, TaxExchangeRate_Date, PricingExchangeRate_SourceCurrencyCode, PricingExchangeRate_TargetCurrencyCode, PricingExchangeRate_CalculationRate, PricingExchangeRate_Date, PaymentExchangeRate_SourceCurrencyCode, PaymentExchangeRate_TargetCurrencyCode, PaymentExchangeRate_CalculationRate, PaymentExchangeRate_Date, PaymentAlternativeExchangeRate_SourceCurrencyCode, PaymentAlternativeExchangeRate_TargetCurrencyCode, PaymentAlternativeExchangeRate_CalculationRate, PaymentAlternativeExchangeRate_Date, TaxAmount, LegalMonetaryTotal_LineExtensionAmount, LegalMonetaryTotal_TaxExclusiveAmount, LegalMonetaryTotal_TaxInclusiveAmount, LegalMonetaryTotal_AllowanceTotalAmount, LegalMonetaryTotal_ChargeTotalAmount, LegalMonetaryTotal_PayableRoundingAmount, LegalMonetaryTotal_PayableAmount, WithholdingTaxAmount, Message) "; 
				cmd.CommandText += " VALUES (@Deleted, " + DF.ActiveConn.UserID + ", GETDATE(), " + DF.ActiveConn.UserID + ", GETDATE(), @IOType, @IntCode, @LocalStatus, @IntegratorID, @Status, @StatusDescription, @PostBox, @XsltNo, @ProfileID, @ID, @UUID, @IssueDate, @IssueTime, @InvoiceTypeCode, @DocumentCurrencyCode, @TaxCurrencyCode, @PricingCurrencyCode, @PaymentCurrencyCode, @PaymentAlternativeCurrencyCode, @LineCountNumeric, @InvoicePeriod_StartDate, @InvoicePeriod_EndDate, @ASP_PartyIdentification1_schemeID, @ASP_PartyIdentification1_ID, @ASP_PartyIdentification2_schemeID, @ASP_PartyIdentification2_ID, @ASP_PartyIdentification3_schemeID, @ASP_PartyIdentification3_ID, @ASP_PartyIdentification4_schemeID, @ASP_PartyIdentification4_ID, @ASP_PartyIdentification5_schemeID, @ASP_PartyIdentification5_ID, @ASP_PartyName, @ASP_PostalAddress_StreetName, @ASP_PostalAddress_Room, @ASP_PostalAddress_BuildingNumber, @ASP_PostalAddress_BuildingName, @ASP_PostalAddress_CitySubdivisionName, @ASP_PostalAddress_CityName, @ASP_PostalAddress_Country, @ASP_PartyTaxSchemeName, @ASP_PartyTaxSchemeTaxTypeCode, @ASP_WebsiteURI, @ASP_Contact_Telephone, @ASP_Contact_Telefax, @ASP_Contact_ElectronicMail, @ASP_Person_FirstName, @ASP_Person_FamilyName, @ASP_Person_MiddleName, @ASP_Person_NameSuffix, @ASP_Person_Title, @ASP_AgentParty_PartyIdentification1_schemeID, @ASP_AgentParty_PartyIdentification1_ID, @ASP_AgentParty_PartyIdentification2_schemeID, @ASP_AgentParty_PartyIdentification2_ID, @ASP_AgentParty_PartyIdentification3_schemeID, @ASP_AgentParty_PartyIdentification3_ID, @ASP_AgentParty_PartyIdentification4_schemeID, @ASP_AgentParty_PartyIdentification4_ID, @ASP_AgentParty_PartyIdentification5_schemeID, @ASP_AgentParty_PartyIdentification5_ID, @ASP_AgentParty_PartyName, @ASP_AgentParty_PostalAddress_StreetName, @ASP_AgentParty_PostalAddress_Room, @ASP_AgentParty_PostalAddress_BuildingNumber, @ASP_AgentParty_PostalAddress_BuildingName, @ASP_AgentParty_PostalAddress_CitySubdivisionName, @ASP_AgentParty_PostalAddress_CityName, @ASP_AgentParty_PostalAddress_Country, @ASP_AgentParty_PartyTaxSchemeName, @ASP_AgentParty_PartyTaxSchemeTaxTypeCode, @ASP_AgentParty_WebsiteURI, @ASP_AgentParty_Contact_Telephone, @ASP_AgentParty_Contact_Telefax, @ASP_AgentParty_Contact_ElectronicMail, @ASP_AgentParty_Person_FirstName, @ASP_AgentParty_Person_FamilyName, @ASP_AgentParty_Person_MiddleName, @ASP_AgentParty_Person_NameSuffix, @ASP_AgentParty_Person_Title, @ACP_PartyIdentification1_schemeID, @ACP_PartyIdentification1_ID, @ACP_PartyIdentification2_schemeID, @ACP_PartyIdentification2_ID, @ACP_PartyIdentification3_schemeID, @ACP_PartyIdentification3_ID, @ACP_PartyIdentification4_schemeID, @ACP_PartyIdentification4_ID, @ACP_PartyIdentification5_schemeID, @ACP_PartyIdentification5_ID, @ACP_PartyName, @ACP_PostalAddress_StreetName, @ACP_PostalAddress_Room, @ACP_PostalAddress_BuildingNumber, @ACP_PostalAddress_BuildingName, @ACP_PostalAddress_CitySubdivisionName, @ACP_PostalAddress_CityName, @ACP_PostalAddress_Country, @ACP_PartyTaxSchemeName, @ACP_PartyTaxSchemeTaxTypeCode, @ACP_WebsiteURI, @ACP_Contact_Telephone, @ACP_Contact_Telefax, @ACP_Contact_ElectronicMail, @ACP_Person_FirstName, @ACP_Person_FamilyName, @ACP_Person_MiddleName, @ACP_Person_NameSuffix, @ACP_Person_Title, @ACP_AgentParty_PartyIdentification1_schemeID, @ACP_AgentParty_PartyIdentification1_ID, @ACP_AgentParty_PartyIdentification2_schemeID, @ACP_AgentParty_PartyIdentification2_ID, @ACP_AgentParty_PartyIdentification3_schemeID, @ACP_AgentParty_PartyIdentification3_ID, @ACP_AgentParty_PartyIdentification4_schemeID, @ACP_AgentParty_PartyIdentification4_ID, @ACP_AgentParty_PartyIdentification5_schemeID, @ACP_AgentParty_PartyIdentification5_ID, @ACP_AgentParty_PartyName, @ACP_AgentParty_PostalAddress_StreetName, @ACP_AgentParty_PostalAddress_Room, @ACP_AgentParty_PostalAddress_BuildingNumber, @ACP_AgentParty_PostalAddress_BuildingName, @ACP_AgentParty_PostalAddress_CitySubdivisionName, @ACP_AgentParty_PostalAddress_CityName, @ACP_AgentParty_PostalAddress_Country, @ACP_AgentParty_PartyTaxSchemeName, @ACP_AgentParty_PartyTaxSchemeTaxTypeCode, @ACP_AgentParty_WebsiteURI, @ACP_AgentParty_Contact_Telephone, @ACP_AgentParty_Contact_Telefax, @ACP_AgentParty_Contact_ElectronicMail, @ACP_AgentParty_Person_FirstName, @ACP_AgentParty_Person_FamilyName, @ACP_AgentParty_Person_MiddleName, @ACP_AgentParty_Person_NameSuffix, @ACP_AgentParty_Person_Title, @TaxExchangeRate_SourceCurrencyCode, @TaxExchangeRate_TargetCurrencyCode, @TaxExchangeRate_CalculationRate, @TaxExchangeRate_Date, @PricingExchangeRate_SourceCurrencyCode, @PricingExchangeRate_TargetCurrencyCode, @PricingExchangeRate_CalculationRate, @PricingExchangeRate_Date, @PaymentExchangeRate_SourceCurrencyCode, @PaymentExchangeRate_TargetCurrencyCode, @PaymentExchangeRate_CalculationRate, @PaymentExchangeRate_Date, @PaymentAlternativeExchangeRate_SourceCurrencyCode, @PaymentAlternativeExchangeRate_TargetCurrencyCode, @PaymentAlternativeExchangeRate_CalculationRate, @PaymentAlternativeExchangeRate_Date, @TaxAmount, @LegalMonetaryTotal_LineExtensionAmount, @LegalMonetaryTotal_TaxExclusiveAmount, @LegalMonetaryTotal_TaxInclusiveAmount, @LegalMonetaryTotal_AllowanceTotalAmount, @LegalMonetaryTotal_ChargeTotalAmount, @LegalMonetaryTotal_PayableRoundingAmount, @LegalMonetaryTotal_PayableAmount, @WithholdingTaxAmount, @Message)"; 
				cmd.CommandText += " SELECT SCOPE_IDENTITY()"; 
				this.InvoiceID = (int)UT.If0Null(cmd.ExecuteScalar());
				if(this.InvoiceID>0)
				{
					return true;
				}
				else
				{
					return false;
				}
			}
			else
			{
				cmd.CommandText = "UPDATE Invoice SET Deleted=@Deleted, ModifiedBy=" + DF.ActiveConn.UserID + ", ModifiedDate=GETDATE(), IOType=@IOType, IntCode=@IntCode, LocalStatus=@LocalStatus, IntegratorID=@IntegratorID, Status=@Status, StatusDescription=@StatusDescription, PostBox=@PostBox, XsltNo=@XsltNo, ProfileID=@ProfileID, ID=@ID, UUID=@UUID, IssueDate=@IssueDate, IssueTime=@IssueTime, InvoiceTypeCode=@InvoiceTypeCode, DocumentCurrencyCode=@DocumentCurrencyCode, TaxCurrencyCode=@TaxCurrencyCode, PricingCurrencyCode=@PricingCurrencyCode, PaymentCurrencyCode=@PaymentCurrencyCode, PaymentAlternativeCurrencyCode=@PaymentAlternativeCurrencyCode, LineCountNumeric=@LineCountNumeric, InvoicePeriod_StartDate=@InvoicePeriod_StartDate, InvoicePeriod_EndDate=@InvoicePeriod_EndDate, ASP_PartyIdentification1_schemeID=@ASP_PartyIdentification1_schemeID, ASP_PartyIdentification1_ID=@ASP_PartyIdentification1_ID, ASP_PartyIdentification2_schemeID=@ASP_PartyIdentification2_schemeID, ASP_PartyIdentification2_ID=@ASP_PartyIdentification2_ID, ASP_PartyIdentification3_schemeID=@ASP_PartyIdentification3_schemeID, ASP_PartyIdentification3_ID=@ASP_PartyIdentification3_ID, ASP_PartyIdentification4_schemeID=@ASP_PartyIdentification4_schemeID, ASP_PartyIdentification4_ID=@ASP_PartyIdentification4_ID, ASP_PartyIdentification5_schemeID=@ASP_PartyIdentification5_schemeID, ASP_PartyIdentification5_ID=@ASP_PartyIdentification5_ID, ASP_PartyName=@ASP_PartyName, ASP_PostalAddress_StreetName=@ASP_PostalAddress_StreetName, ASP_PostalAddress_Room=@ASP_PostalAddress_Room, ASP_PostalAddress_BuildingNumber=@ASP_PostalAddress_BuildingNumber, ASP_PostalAddress_BuildingName=@ASP_PostalAddress_BuildingName, ASP_PostalAddress_CitySubdivisionName=@ASP_PostalAddress_CitySubdivisionName, ASP_PostalAddress_CityName=@ASP_PostalAddress_CityName, ASP_PostalAddress_Country=@ASP_PostalAddress_Country, ASP_PartyTaxSchemeName=@ASP_PartyTaxSchemeName, ASP_PartyTaxSchemeTaxTypeCode=@ASP_PartyTaxSchemeTaxTypeCode, ASP_WebsiteURI=@ASP_WebsiteURI, ASP_Contact_Telephone=@ASP_Contact_Telephone, ASP_Contact_Telefax=@ASP_Contact_Telefax, ASP_Contact_ElectronicMail=@ASP_Contact_ElectronicMail, ASP_Person_FirstName=@ASP_Person_FirstName, ASP_Person_FamilyName=@ASP_Person_FamilyName, ASP_Person_MiddleName=@ASP_Person_MiddleName, ASP_Person_NameSuffix=@ASP_Person_NameSuffix, ASP_Person_Title=@ASP_Person_Title, ASP_AgentParty_PartyIdentification1_schemeID=@ASP_AgentParty_PartyIdentification1_schemeID, ASP_AgentParty_PartyIdentification1_ID=@ASP_AgentParty_PartyIdentification1_ID, ASP_AgentParty_PartyIdentification2_schemeID=@ASP_AgentParty_PartyIdentification2_schemeID, ASP_AgentParty_PartyIdentification2_ID=@ASP_AgentParty_PartyIdentification2_ID, ASP_AgentParty_PartyIdentification3_schemeID=@ASP_AgentParty_PartyIdentification3_schemeID, ASP_AgentParty_PartyIdentification3_ID=@ASP_AgentParty_PartyIdentification3_ID, ASP_AgentParty_PartyIdentification4_schemeID=@ASP_AgentParty_PartyIdentification4_schemeID, ASP_AgentParty_PartyIdentification4_ID=@ASP_AgentParty_PartyIdentification4_ID, ASP_AgentParty_PartyIdentification5_schemeID=@ASP_AgentParty_PartyIdentification5_schemeID, ASP_AgentParty_PartyIdentification5_ID=@ASP_AgentParty_PartyIdentification5_ID, ASP_AgentParty_PartyName=@ASP_AgentParty_PartyName, ASP_AgentParty_PostalAddress_StreetName=@ASP_AgentParty_PostalAddress_StreetName, ASP_AgentParty_PostalAddress_Room=@ASP_AgentParty_PostalAddress_Room, ASP_AgentParty_PostalAddress_BuildingNumber=@ASP_AgentParty_PostalAddress_BuildingNumber, ASP_AgentParty_PostalAddress_BuildingName=@ASP_AgentParty_PostalAddress_BuildingName, ASP_AgentParty_PostalAddress_CitySubdivisionName=@ASP_AgentParty_PostalAddress_CitySubdivisionName, ASP_AgentParty_PostalAddress_CityName=@ASP_AgentParty_PostalAddress_CityName, ASP_AgentParty_PostalAddress_Country=@ASP_AgentParty_PostalAddress_Country, ASP_AgentParty_PartyTaxSchemeName=@ASP_AgentParty_PartyTaxSchemeName, ASP_AgentParty_PartyTaxSchemeTaxTypeCode=@ASP_AgentParty_PartyTaxSchemeTaxTypeCode, ASP_AgentParty_WebsiteURI=@ASP_AgentParty_WebsiteURI, ASP_AgentParty_Contact_Telephone=@ASP_AgentParty_Contact_Telephone, ASP_AgentParty_Contact_Telefax=@ASP_AgentParty_Contact_Telefax, ASP_AgentParty_Contact_ElectronicMail=@ASP_AgentParty_Contact_ElectronicMail, ASP_AgentParty_Person_FirstName=@ASP_AgentParty_Person_FirstName, ASP_AgentParty_Person_FamilyName=@ASP_AgentParty_Person_FamilyName, ASP_AgentParty_Person_MiddleName=@ASP_AgentParty_Person_MiddleName, ASP_AgentParty_Person_NameSuffix=@ASP_AgentParty_Person_NameSuffix, ASP_AgentParty_Person_Title=@ASP_AgentParty_Person_Title, ACP_PartyIdentification1_schemeID=@ACP_PartyIdentification1_schemeID, ACP_PartyIdentification1_ID=@ACP_PartyIdentification1_ID, ACP_PartyIdentification2_schemeID=@ACP_PartyIdentification2_schemeID, ACP_PartyIdentification2_ID=@ACP_PartyIdentification2_ID, ACP_PartyIdentification3_schemeID=@ACP_PartyIdentification3_schemeID, ACP_PartyIdentification3_ID=@ACP_PartyIdentification3_ID, ACP_PartyIdentification4_schemeID=@ACP_PartyIdentification4_schemeID, ACP_PartyIdentification4_ID=@ACP_PartyIdentification4_ID, ACP_PartyIdentification5_schemeID=@ACP_PartyIdentification5_schemeID, ACP_PartyIdentification5_ID=@ACP_PartyIdentification5_ID, ACP_PartyName=@ACP_PartyName, ACP_PostalAddress_StreetName=@ACP_PostalAddress_StreetName, ACP_PostalAddress_Room=@ACP_PostalAddress_Room, ACP_PostalAddress_BuildingNumber=@ACP_PostalAddress_BuildingNumber, ACP_PostalAddress_BuildingName=@ACP_PostalAddress_BuildingName, ACP_PostalAddress_CitySubdivisionName=@ACP_PostalAddress_CitySubdivisionName, ACP_PostalAddress_CityName=@ACP_PostalAddress_CityName, ACP_PostalAddress_Country=@ACP_PostalAddress_Country, ACP_PartyTaxSchemeName=@ACP_PartyTaxSchemeName, ACP_PartyTaxSchemeTaxTypeCode=@ACP_PartyTaxSchemeTaxTypeCode, ACP_WebsiteURI=@ACP_WebsiteURI, ACP_Contact_Telephone=@ACP_Contact_Telephone, ACP_Contact_Telefax=@ACP_Contact_Telefax, ACP_Contact_ElectronicMail=@ACP_Contact_ElectronicMail, ACP_Person_FirstName=@ACP_Person_FirstName, ACP_Person_FamilyName=@ACP_Person_FamilyName, ACP_Person_MiddleName=@ACP_Person_MiddleName, ACP_Person_NameSuffix=@ACP_Person_NameSuffix, ACP_Person_Title=@ACP_Person_Title, ACP_AgentParty_PartyIdentification1_schemeID=@ACP_AgentParty_PartyIdentification1_schemeID, ACP_AgentParty_PartyIdentification1_ID=@ACP_AgentParty_PartyIdentification1_ID, ACP_AgentParty_PartyIdentification2_schemeID=@ACP_AgentParty_PartyIdentification2_schemeID, ACP_AgentParty_PartyIdentification2_ID=@ACP_AgentParty_PartyIdentification2_ID, ACP_AgentParty_PartyIdentification3_schemeID=@ACP_AgentParty_PartyIdentification3_schemeID, ACP_AgentParty_PartyIdentification3_ID=@ACP_AgentParty_PartyIdentification3_ID, ACP_AgentParty_PartyIdentification4_schemeID=@ACP_AgentParty_PartyIdentification4_schemeID, ACP_AgentParty_PartyIdentification4_ID=@ACP_AgentParty_PartyIdentification4_ID, ACP_AgentParty_PartyIdentification5_schemeID=@ACP_AgentParty_PartyIdentification5_schemeID, ACP_AgentParty_PartyIdentification5_ID=@ACP_AgentParty_PartyIdentification5_ID, ACP_AgentParty_PartyName=@ACP_AgentParty_PartyName, ACP_AgentParty_PostalAddress_StreetName=@ACP_AgentParty_PostalAddress_StreetName, ACP_AgentParty_PostalAddress_Room=@ACP_AgentParty_PostalAddress_Room, ACP_AgentParty_PostalAddress_BuildingNumber=@ACP_AgentParty_PostalAddress_BuildingNumber, ACP_AgentParty_PostalAddress_BuildingName=@ACP_AgentParty_PostalAddress_BuildingName, ACP_AgentParty_PostalAddress_CitySubdivisionName=@ACP_AgentParty_PostalAddress_CitySubdivisionName, ACP_AgentParty_PostalAddress_CityName=@ACP_AgentParty_PostalAddress_CityName, ACP_AgentParty_PostalAddress_Country=@ACP_AgentParty_PostalAddress_Country, ACP_AgentParty_PartyTaxSchemeName=@ACP_AgentParty_PartyTaxSchemeName, ACP_AgentParty_PartyTaxSchemeTaxTypeCode=@ACP_AgentParty_PartyTaxSchemeTaxTypeCode, ACP_AgentParty_WebsiteURI=@ACP_AgentParty_WebsiteURI, ACP_AgentParty_Contact_Telephone=@ACP_AgentParty_Contact_Telephone, ACP_AgentParty_Contact_Telefax=@ACP_AgentParty_Contact_Telefax, ACP_AgentParty_Contact_ElectronicMail=@ACP_AgentParty_Contact_ElectronicMail, ACP_AgentParty_Person_FirstName=@ACP_AgentParty_Person_FirstName, ACP_AgentParty_Person_FamilyName=@ACP_AgentParty_Person_FamilyName, ACP_AgentParty_Person_MiddleName=@ACP_AgentParty_Person_MiddleName, ACP_AgentParty_Person_NameSuffix=@ACP_AgentParty_Person_NameSuffix, ACP_AgentParty_Person_Title=@ACP_AgentParty_Person_Title, TaxExchangeRate_SourceCurrencyCode=@TaxExchangeRate_SourceCurrencyCode, TaxExchangeRate_TargetCurrencyCode=@TaxExchangeRate_TargetCurrencyCode, TaxExchangeRate_CalculationRate=@TaxExchangeRate_CalculationRate, TaxExchangeRate_Date=@TaxExchangeRate_Date, PricingExchangeRate_SourceCurrencyCode=@PricingExchangeRate_SourceCurrencyCode, PricingExchangeRate_TargetCurrencyCode=@PricingExchangeRate_TargetCurrencyCode, PricingExchangeRate_CalculationRate=@PricingExchangeRate_CalculationRate, PricingExchangeRate_Date=@PricingExchangeRate_Date, PaymentExchangeRate_SourceCurrencyCode=@PaymentExchangeRate_SourceCurrencyCode, PaymentExchangeRate_TargetCurrencyCode=@PaymentExchangeRate_TargetCurrencyCode, PaymentExchangeRate_CalculationRate=@PaymentExchangeRate_CalculationRate, PaymentExchangeRate_Date=@PaymentExchangeRate_Date, PaymentAlternativeExchangeRate_SourceCurrencyCode=@PaymentAlternativeExchangeRate_SourceCurrencyCode, PaymentAlternativeExchangeRate_TargetCurrencyCode=@PaymentAlternativeExchangeRate_TargetCurrencyCode, PaymentAlternativeExchangeRate_CalculationRate=@PaymentAlternativeExchangeRate_CalculationRate, PaymentAlternativeExchangeRate_Date=@PaymentAlternativeExchangeRate_Date, TaxAmount=@TaxAmount, LegalMonetaryTotal_LineExtensionAmount=@LegalMonetaryTotal_LineExtensionAmount, LegalMonetaryTotal_TaxExclusiveAmount=@LegalMonetaryTotal_TaxExclusiveAmount, LegalMonetaryTotal_TaxInclusiveAmount=@LegalMonetaryTotal_TaxInclusiveAmount, LegalMonetaryTotal_AllowanceTotalAmount=@LegalMonetaryTotal_AllowanceTotalAmount, LegalMonetaryTotal_ChargeTotalAmount=@LegalMonetaryTotal_ChargeTotalAmount, LegalMonetaryTotal_PayableRoundingAmount=@LegalMonetaryTotal_PayableRoundingAmount, LegalMonetaryTotal_PayableAmount=@LegalMonetaryTotal_PayableAmount, WithholdingTaxAmount=@WithholdingTaxAmount, Message=@Message ";
				cmd.CommandText += "WHERE InvoiceID = " + this.InvoiceID;
				if(cmd.ExecuteNonQuery()>0)
				{
					return true;
				}
				else
				{
					return false;
				}
			}
		}
	}
}


