//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrTEK_EFatura.FinansbankUser {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.csap.cs.com.tr/", ConfigurationName="FinansbankUser.UserService")]
    public interface UserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.csap.cs.com.tr/UserService/logoutRequest", ReplyAction="http://service.csap.cs.com.tr/UserService/logoutResponse")]
        void logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.csap.cs.com.tr/UserService/logoutRequest", ReplyAction="http://service.csap.cs.com.tr/UserService/logoutResponse")]
        System.Threading.Tasks.Task logoutAsync();
        
        // CODEGEN: Generating message contract since element name userId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.csap.cs.com.tr/UserService/wsLoginRequest", ReplyAction="http://service.csap.cs.com.tr/UserService/wsLoginResponse")]
        MrTEK_EFatura.FinansbankUser.wsLoginResponse wsLogin(MrTEK_EFatura.FinansbankUser.wsLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.csap.cs.com.tr/UserService/wsLoginRequest", ReplyAction="http://service.csap.cs.com.tr/UserService/wsLoginResponse")]
        System.Threading.Tasks.Task<MrTEK_EFatura.FinansbankUser.wsLoginResponse> wsLoginAsync(MrTEK_EFatura.FinansbankUser.wsLoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsLogin", Namespace="http://service.csap.cs.com.tr/", Order=0)]
        public MrTEK_EFatura.FinansbankUser.wsLoginRequestBody Body;
        
        public wsLoginRequest() {
        }
        
        public wsLoginRequest(MrTEK_EFatura.FinansbankUser.wsLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class wsLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lang;
        
        public wsLoginRequestBody() {
        }
        
        public wsLoginRequestBody(string userId, string password, string lang) {
            this.userId = userId;
            this.password = password;
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsLoginResponse", Namespace="http://service.csap.cs.com.tr/", Order=0)]
        public MrTEK_EFatura.FinansbankUser.wsLoginResponseBody Body;
        
        public wsLoginResponse() {
        }
        
        public wsLoginResponse(MrTEK_EFatura.FinansbankUser.wsLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class wsLoginResponseBody {
        
        public wsLoginResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceChannel : MrTEK_EFatura.FinansbankUser.UserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<MrTEK_EFatura.FinansbankUser.UserService>, MrTEK_EFatura.FinansbankUser.UserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void logout() {
            base.Channel.logout();
        }
        
        public System.Threading.Tasks.Task logoutAsync() {
            return base.Channel.logoutAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrTEK_EFatura.FinansbankUser.wsLoginResponse MrTEK_EFatura.FinansbankUser.UserService.wsLogin(MrTEK_EFatura.FinansbankUser.wsLoginRequest request) {
            return base.Channel.wsLogin(request);
        }
        
        public void wsLogin(string userId, string password, string lang) {
            MrTEK_EFatura.FinansbankUser.wsLoginRequest inValue = new MrTEK_EFatura.FinansbankUser.wsLoginRequest();
            inValue.Body = new MrTEK_EFatura.FinansbankUser.wsLoginRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.lang = lang;
            MrTEK_EFatura.FinansbankUser.wsLoginResponse retVal = ((MrTEK_EFatura.FinansbankUser.UserService)(this)).wsLogin(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MrTEK_EFatura.FinansbankUser.wsLoginResponse> MrTEK_EFatura.FinansbankUser.UserService.wsLoginAsync(MrTEK_EFatura.FinansbankUser.wsLoginRequest request) {
            return base.Channel.wsLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<MrTEK_EFatura.FinansbankUser.wsLoginResponse> wsLoginAsync(string userId, string password, string lang) {
            MrTEK_EFatura.FinansbankUser.wsLoginRequest inValue = new MrTEK_EFatura.FinansbankUser.wsLoginRequest();
            inValue.Body = new MrTEK_EFatura.FinansbankUser.wsLoginRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.lang = lang;
            return ((MrTEK_EFatura.FinansbankUser.UserService)(this)).wsLoginAsync(inValue);
        }
    }
}
